//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF.Cliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteENT", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class ClienteENT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exento {
            get {
                return this.ExentoField;
            }
            set {
                if ((this.ExentoField.Equals(value) != true)) {
                    this.ExentoField = value;
                    this.RaisePropertyChanged("Exento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteCuentaView", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class ClienteCuentaView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BancoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuentaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco {
            get {
                return this.BancoField;
            }
            set {
                if ((object.ReferenceEquals(this.BancoField, value) != true)) {
                    this.BancoField = value;
                    this.RaisePropertyChanged("Banco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BancoId {
            get {
                return this.BancoIdField;
            }
            set {
                if ((this.BancoIdField.Equals(value) != true)) {
                    this.BancoIdField = value;
                    this.RaisePropertyChanged("BancoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CuentaId {
            get {
                return this.CuentaIdField;
            }
            set {
                if ((this.CuentaIdField.Equals(value) != true)) {
                    this.CuentaIdField = value;
                    this.RaisePropertyChanged("CuentaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaENT", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class CuentaENT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BancoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuentaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BancoId {
            get {
                return this.BancoIdField;
            }
            set {
                if ((this.BancoIdField.Equals(value) != true)) {
                    this.BancoIdField = value;
                    this.RaisePropertyChanged("BancoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CuentaId {
            get {
                return this.CuentaIdField;
            }
            set {
                if ((this.CuentaIdField.Equals(value) != true)) {
                    this.CuentaIdField = value;
                    this.RaisePropertyChanged("CuentaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cliente.IClienteWCF")]
    public interface IClienteWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/Loguear", ReplyAction="http://tempuri.org/IClienteWCF/LoguearResponse")]
        int Loguear(WF.Cliente.ClienteENT clienteENT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/Loguear", ReplyAction="http://tempuri.org/IClienteWCF/LoguearResponse")]
        System.Threading.Tasks.Task<int> LoguearAsync(WF.Cliente.ClienteENT clienteENT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/GetClienteCuenta", ReplyAction="http://tempuri.org/IClienteWCF/GetClienteCuentaResponse")]
        WF.Cliente.ClienteCuentaView[] GetClienteCuenta(WF.Cliente.ClienteCuentaView clienteCuentaView);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/GetClienteCuenta", ReplyAction="http://tempuri.org/IClienteWCF/GetClienteCuentaResponse")]
        System.Threading.Tasks.Task<WF.Cliente.ClienteCuentaView[]> GetClienteCuentaAsync(WF.Cliente.ClienteCuentaView clienteCuentaView);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/GetClienteSesion", ReplyAction="http://tempuri.org/IClienteWCF/GetClienteSesionResponse")]
        WF.Cliente.ClienteENT GetClienteSesion(WF.Cliente.ClienteENT cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/GetClienteSesion", ReplyAction="http://tempuri.org/IClienteWCF/GetClienteSesionResponse")]
        System.Threading.Tasks.Task<WF.Cliente.ClienteENT> GetClienteSesionAsync(WF.Cliente.ClienteENT cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/GetCuentas", ReplyAction="http://tempuri.org/IClienteWCF/GetCuentasResponse")]
        WF.Cliente.CuentaENT[] GetCuentas(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteWCF/GetCuentas", ReplyAction="http://tempuri.org/IClienteWCF/GetCuentasResponse")]
        System.Threading.Tasks.Task<WF.Cliente.CuentaENT[]> GetCuentasAsync(string numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteWCFChannel : WF.Cliente.IClienteWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWCFClient : System.ServiceModel.ClientBase<WF.Cliente.IClienteWCF>, WF.Cliente.IClienteWCF {
        
        public ClienteWCFClient() {
        }
        
        public ClienteWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Loguear(WF.Cliente.ClienteENT clienteENT) {
            return base.Channel.Loguear(clienteENT);
        }
        
        public System.Threading.Tasks.Task<int> LoguearAsync(WF.Cliente.ClienteENT clienteENT) {
            return base.Channel.LoguearAsync(clienteENT);
        }
        
        public WF.Cliente.ClienteCuentaView[] GetClienteCuenta(WF.Cliente.ClienteCuentaView clienteCuentaView) {
            return base.Channel.GetClienteCuenta(clienteCuentaView);
        }
        
        public System.Threading.Tasks.Task<WF.Cliente.ClienteCuentaView[]> GetClienteCuentaAsync(WF.Cliente.ClienteCuentaView clienteCuentaView) {
            return base.Channel.GetClienteCuentaAsync(clienteCuentaView);
        }
        
        public WF.Cliente.ClienteENT GetClienteSesion(WF.Cliente.ClienteENT cliente) {
            return base.Channel.GetClienteSesion(cliente);
        }
        
        public System.Threading.Tasks.Task<WF.Cliente.ClienteENT> GetClienteSesionAsync(WF.Cliente.ClienteENT cliente) {
            return base.Channel.GetClienteSesionAsync(cliente);
        }
        
        public WF.Cliente.CuentaENT[] GetCuentas(string numero) {
            return base.Channel.GetCuentas(numero);
        }
        
        public System.Threading.Tasks.Task<WF.Cliente.CuentaENT[]> GetCuentasAsync(string numero) {
            return base.Channel.GetCuentasAsync(numero);
        }
    }
}
