//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF.Movimiento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoENT", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class MovimientoENT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CuentaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CuentaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GmfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CuentaDestino {
            get {
                return this.CuentaDestinoField;
            }
            set {
                if ((this.CuentaDestinoField.Equals(value) != true)) {
                    this.CuentaDestinoField = value;
                    this.RaisePropertyChanged("CuentaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CuentaOrigen {
            get {
                return this.CuentaOrigenField;
            }
            set {
                if ((this.CuentaOrigenField.Equals(value) != true)) {
                    this.CuentaOrigenField = value;
                    this.RaisePropertyChanged("CuentaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gmf {
            get {
                return this.GmfField;
            }
            set {
                if ((this.GmfField.Equals(value) != true)) {
                    this.GmfField = value;
                    this.RaisePropertyChanged("Gmf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoView", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class MovimientoView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GmfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaDestino {
            get {
                return this.CuentaDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaDestinoField, value) != true)) {
                    this.CuentaDestinoField = value;
                    this.RaisePropertyChanged("CuentaDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaOrigen {
            get {
                return this.CuentaOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaOrigenField, value) != true)) {
                    this.CuentaOrigenField = value;
                    this.RaisePropertyChanged("CuentaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gmf {
            get {
                return this.GmfField;
            }
            set {
                if ((this.GmfField.Equals(value) != true)) {
                    this.GmfField = value;
                    this.RaisePropertyChanged("Gmf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Movimiento.IMovimiento")]
    public interface IMovimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento/Transferir", ReplyAction="http://tempuri.org/IMovimiento/TransferirResponse")]
        int Transferir(WF.Movimiento.MovimientoENT movimientoENT, bool exento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento/Transferir", ReplyAction="http://tempuri.org/IMovimiento/TransferirResponse")]
        System.Threading.Tasks.Task<int> TransferirAsync(WF.Movimiento.MovimientoENT movimientoENT, bool exento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento/GetMovimientos", ReplyAction="http://tempuri.org/IMovimiento/GetMovimientosResponse")]
        WF.Movimiento.MovimientoView[] GetMovimientos(WF.Movimiento.MovimientoView movimientoView);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovimiento/GetMovimientos", ReplyAction="http://tempuri.org/IMovimiento/GetMovimientosResponse")]
        System.Threading.Tasks.Task<WF.Movimiento.MovimientoView[]> GetMovimientosAsync(WF.Movimiento.MovimientoView movimientoView);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovimientoChannel : WF.Movimiento.IMovimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovimientoClient : System.ServiceModel.ClientBase<WF.Movimiento.IMovimiento>, WF.Movimiento.IMovimiento {
        
        public MovimientoClient() {
        }
        
        public MovimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Transferir(WF.Movimiento.MovimientoENT movimientoENT, bool exento) {
            return base.Channel.Transferir(movimientoENT, exento);
        }
        
        public System.Threading.Tasks.Task<int> TransferirAsync(WF.Movimiento.MovimientoENT movimientoENT, bool exento) {
            return base.Channel.TransferirAsync(movimientoENT, exento);
        }
        
        public WF.Movimiento.MovimientoView[] GetMovimientos(WF.Movimiento.MovimientoView movimientoView) {
            return base.Channel.GetMovimientos(movimientoView);
        }
        
        public System.Threading.Tasks.Task<WF.Movimiento.MovimientoView[]> GetMovimientosAsync(WF.Movimiento.MovimientoView movimientoView) {
            return base.Channel.GetMovimientosAsync(movimientoView);
        }
    }
}
